# Generated by Django 3.0.8 on 2020-10-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listcus',
            name='is_lock',
        ),
        migrations.AddField(
            model_name='typeproduct',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
