# Generated by Django 3.0.8 on 2020-10-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_auto_20201027_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcus',
            name='is_lock',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
