# Generated by Django 3.0.8 on 2020-10-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_listcus_is_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeproduct',
            name='is_show',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
