# Generated by Django 3.0.8 on 2020-11-05 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0005_typelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='cus_ttpp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cus_ttpp', to='Service.ListCus'),
        ),
    ]
