# Generated by Django 3.0.8 on 2020-11-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0006_report_cus_ttpp'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='type',
            field=models.IntegerField(blank=True, choices=[[1, 'Hóa đơn'], [2, 'Bảng kê'], [3, 'Biên bản'], [4, 'Khác']], null=True),
        ),
    ]
