# Generated by Django 3.0.8 on 2020-11-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0008_usercoop_is_take_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcus',
            name='id_old',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
