# Generated by Django 3.0.8 on 2021-04-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0009_listcus_id_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusbill',
            name='stt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
